apiVersion: v1
kind: Service
metadata:
  name: timeloss-dot-run-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: timeloss-dot-run
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeloss-dot-run
  labels:
    app: timeloss-dot-run
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeloss-dot-run
  template:
    metadata:
      labels:
        app: timeloss-dot-run
    spec:
      containers:
      - name: timeloss-dot-run
        image: corvimae/timeloss-dot-run:latest
        ports:
        - containerPort: 3000